# Generated by Django 5.2.5 on 2025-08-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtendedPermissions',
            new_name='ExtendedPermission',
        ),
        migrations.RenameIndex(
            model_name='extendedpermission',
            new_name='users_exten_user_id_d9b8b3_idx',
            old_name='users_exten_user_id_4c2bac_idx',
        ),
    ]
