# Generated by Django 5.2.5 on 2025-08-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='billing_wal_status__154f26_idx',
            old_name='billing_wal_status_276c8d_idx',
        ),
        migrations.AddField(
            model_name='walletaccount',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
    ]
