# Generated by Django 5.2.5 on 2025-08-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_billing_wal_status_276c8d_idx_billing_wal_status__154f26_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='receipt_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
