# Generated by Django 5.2.5 on 2025-08-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_wallettransaction_receipt_number'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='walletaccount',
            new_name='billing_wal_current_4f6737_idx',
            old_name='billing_wal_current_d15589_idx',
        ),
    ]
