# Generated by Django 5.2.5 on 2025-08-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rename_billing_wal_current_d15589_idx_billing_wal_current_4f6737_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='charge',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
