# Generated by Django 5.2.5 on 2025-08-17 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_balanceentrytype_state_entrytype_state_and_more'),
        ('billing', '0005_wallettransaction_charge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('pledger_name', models.CharField(help_text='Person/Organization making the pledge', max_length=255)),
                ('pledger_contact', models.CharField(blank=True, help_text='Phone/email of the pledger', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField(blank=True, help_text='What is this pledge for?', null=True)),
                ('planned_clear_date', models.DateField(blank=True, help_text='When the pledger intends to clear the pledge', null=True)),
                ('raised_by', models.ForeignKey(help_text='User who recorded this pledge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges_raised', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PledgeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount recorded', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Remaining pledge balance after this payment', max_digits=12)),
                ('note', models.TextField(blank=True, help_text='Optional note about this payment', null=True)),
                ('logged_by', models.ForeignKey(blank=True, help_text='User who logged this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledge_logs', to=settings.AUTH_USER_MODEL)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='billing.pledge')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
