# Generated by Django 5.2.5 on 2025-08-17 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_pledge_pledgelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='raised_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded this pledge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges_raised', to=settings.AUTH_USER_MODEL),
        ),
    ]
