# Generated by Django 5.2.5 on 2025-08-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_pledge_raised_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='raised_by',
            field=models.CharField(blank=True, help_text='User who raised this pledge', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pledgelog',
            name='logged_by',
            field=models.CharField(blank=True, help_text='User who logged this pledge', max_length=100, null=True),
        ),
    ]
