# Generated by Django 5.2.5 on 2025-08-17 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_pledge_raised_by_alter_pledgelog_logged_by'),
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.contribution'),
        ),
    ]
