# Generated by Django 5.2.5 on 2025-08-17 20:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_pledge_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='amount_plus_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
    ]
