# Generated by Django 5.2.5 on 2025-08-22 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_wallettransaction_actioned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'TopUp'), ('payment', 'Payment'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Manual Adjustment'), ('refund', 'Refund')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowactionlog',
            name='action_type',
            field=models.CharField(choices=[('money_to_uncleared', 'Money Added to Uncleared'), ('money_to_current', 'Money Added to Current'), ('money_from_uncleared', 'Money Deducted from Uncleared'), ('money_to_available', 'Money Added to Available'), ('money_from_available', 'Money Deducted from Available'), ('money_to_reserved', 'Money Added to Reserved'), ('money_from_reserved', 'Money Deducted from Reserved'), ('money_from_current', 'Money Deducted from Current'), ('money_for_withdrawal', 'Money Prepared for Withdrawal'), ('charge_deducted', 'Charge Deducted for Withdrawal')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='RevenueLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('revenue_type', models.CharField(choices=[('topup_charge', 'TopUp Charge'), ('withdrawal_charge', 'Withdrawal Charge'), ('adjustment', 'Manual Adjustment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Original transaction amount before charge', max_digits=18)),
                ('charge_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Rate used to calculate charge (e.g., 0.01 for 1%)', max_digits=5, null=True)),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_logs', to='billing.wallettransaction')),
                ('wallet_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_logs', to='billing.walletaccount')),
            ],
            options={
                'verbose_name': 'Revenue Log',
                'verbose_name_plural': 'Revenue Logs',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['wallet_account', '-id'], name='billing_rev_wallet__26f626_idx'), models.Index(fields=['parent_transaction', '-id'], name='billing_rev_parent__f17a04_idx'), models.Index(fields=['revenue_type', '-id'], name='billing_rev_revenue_a0089e_idx'), models.Index(fields=['date_created'], name='billing_rev_date_cr_71ce85_idx'), models.Index(fields=['reference'], name='billing_rev_referen_09a2de_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='positive_revenue_amount'), models.CheckConstraint(condition=models.Q(('original_amount__gte', 0)), name='positive_original_amount')],
            },
        ),
    ]
