# Generated by Django 5.2.5 on 2025-08-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
