# Generated by Django 5.2.5 on 2025-10-06 09:30

import contributions.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_contribution_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='profile',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/srv/documents'), upload_to=contributions.models.default_uploads_to),
        ),
    ]
