# Generated by Django 5.2.5 on 2025-10-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_contribution_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
