# Generated by Django 5.2.5 on 2025-10-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_contribution_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='description',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
