# Generated by Django 5.2.5 on 2025-10-22 09:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Name of the external system or partner.', max_length=100, unique=True)),
                ('api_key', models.CharField(editable=False, help_text='Unique API key identifying this client.', max_length=64, unique=True)),
                ('allowed_ips', models.TextField(blank=True, help_text='Comma-separated list of allowed IPs for request validation.')),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata about the client (contact info, environment, etc.).', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'API Client',
                'verbose_name_plural': 'API Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('user', 'Per User'), ('ip', 'Per IP'), ('endpoint', 'Per Endpoint'), ('user_endpoint', 'Per User + Endpoint'), ('ip_endpoint', 'Per IP + Endpoint')], max_length=20)),
                ('limit', models.PositiveIntegerField(help_text='Number of requests allowed')),
                ('period', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10)),
                ('period_count', models.PositiveIntegerField(default=1, help_text="Number of periods (e.g., 2 for '2 hours')")),
                ('endpoint_pattern', models.CharField(blank=True, help_text='Regex pattern for URL matching', max_length=200)),
                ('http_methods', models.CharField(blank=True, help_text='Comma-separated HTTP methods (GET,POST,etc)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are checked first')),
                ('block_duration_minutes', models.PositiveIntegerField(default=0, help_text='Block duration after limit exceeded (0 = no blocking)')),
            ],
            options={
                'ordering': ['name', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='SystemKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('public_key', models.TextField(help_text='Public key (shared with partners).')),
                ('private_key', models.TextField(help_text='Private key')),
                ('fingerprint', models.CharField(help_text='SHA-256 fingerprint of the public key.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Key',
                'verbose_name_plural': 'System Keys',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ApiClientKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('public_key', models.TextField(help_text="The client's public key in PEM format.")),
                ('fingerprint', models.CharField(db_index=True, help_text='SHA-256 fingerprint of the public key for quick lookup.', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this key is the current active key for the client.')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(help_text='Owning API client for this key.', on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='api.apiclient')),
            ],
            options={
                'verbose_name': 'API Client Key',
                'verbose_name_plural': 'API Client Keys',
                'ordering': ['-date_created'],
                'unique_together': {('client', 'fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='RateLimitBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('blocked_until', models.DateTimeField(db_index=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ratelimitrule')),
            ],
            options={
                'ordering': ['-date_modified'],
                'unique_together': {('rule', 'key', 'endpoint')},
            },
        ),
        migrations.CreateModel(
            name='RateLimitAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('count', models.PositiveIntegerField(default=1)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ratelimitrule')),
            ],
            options={
                'ordering': ['-last_attempt'],
                'indexes': [models.Index(fields=['rule', 'key', 'window_start'], name='api_ratelim_rule_id_17416a_idx'), models.Index(fields=['window_start'], name='api_ratelim_window__d28eae_idx')],
                'unique_together': {('rule', 'key', 'endpoint', 'window_start')},
            },
        ),
    ]
