# Generated by Django 5.2.5 on 2025-10-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratelimitrule',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('api_client', 'API Client'), ('user', 'Per User'), ('ip', 'Per IP'), ('endpoint', 'Per Endpoint'), ('api_client_endpoint', 'Per API Client + Endpoint'), ('user_endpoint', 'Per User + Endpoint'), ('ip_endpoint', 'Per IP + Endpoint')], max_length=20),
        ),
    ]
