# Generated by Django 5.2.5 on 2025-10-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ratelimitrule_scope'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratelimitblock',
            unique_together={('rule', 'key')},
        ),
        migrations.RemoveField(
            model_name='ratelimitblock',
            name='endpoint',
        ),
    ]
