# Generated by Django 5.2.5 on 2025-11-05 08:09

import audit.mixins
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ratelimitblock_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclientkey',
            name='signature_header_key',
            field=models.CharField(default='x-signature', help_text='Header name containing the signature value.', max_length=50),
        ),
        migrations.AddField(
            model_name='apiclientkey',
            name='signature_secret',
            field=models.CharField(blank=True, help_text='Signing key.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apiclientkey',
            name='signature_type',
            field=models.CharField(choices=[('HMAC', 'HMAC'), ('RSA', 'RSA')], default='HMAC', help_text='Algorithm used for signature verification.', max_length=20),
        ),
        migrations.AlterField(
            model_name='apiclientkey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if this client is active.'),
        ),
        migrations.CreateModel(
            name='APICallback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('path', models.CharField(help_text='URL path pattern or endpoint for the callback.', max_length=255, unique=True)),
                ('require_authentication', models.BooleanField(default=False, help_text='If True, the callback requires API key authentication.')),
                ('require_signature_verification', models.BooleanField(default=False, help_text='If True, incoming requests must include a valid cryptographic signature.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this callback is active.')),
                ('client', models.ForeignKey(help_text='API client associated with this callback.', on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='api.apiclient')),
            ],
            options={
                'verbose_name': 'API Callback',
                'verbose_name_plural': 'API Callbacks',
                'ordering': ['client__name', 'path'],
                'unique_together': {('client', 'path')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
    ]
