# Generated by Django 5.2.5 on 2025-11-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apiclientkey_signature_header_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiclientkey',
            name='signature_header_key',
        ),
        migrations.RemoveField(
            model_name='apiclientkey',
            name='signature_secret',
        ),
        migrations.RemoveField(
            model_name='apiclientkey',
            name='signature_type',
        ),
        migrations.AddField(
            model_name='apiclient',
            name='require_signature_verification',
            field=models.BooleanField(default=False, help_text='If True, incoming requests must include a valid cryptographic signature.'),
        ),
        migrations.AddField(
            model_name='apiclient',
            name='signature_algorithm',
            field=models.CharField(choices=[('HMAC-SHA256', 'HMAC-SHA256'), ('RSA-SHA256', 'RSA-SHA256')], default='HMAC-SHA256', help_text='Algorithm used to verify callback signatures.', max_length=20),
        ),
        migrations.AddField(
            model_name='apiclient',
            name='signature_header_key',
            field=models.CharField(default='x-signature', help_text='Header name containing the callback signature.', max_length=50),
        ),
        migrations.AddField(
            model_name='apiclient',
            name='signature_secret',
            field=models.CharField(blank=True, help_text='Shared secret for HMAC signature validation of callbacks.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apiclientkey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if this key is currently active.'),
        ),
    ]
