# Generated by Django 5.2.5 on 2025-11-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_apiclientkey_signature_header_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicallback',
            name='require_signature_verification',
        ),
    ]
