# Generated by Django 5.2.5 on 2025-08-09 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVATION_PENDING', 'Activation Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='ACTIVATION_PENDING', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Identities',
                'ordering': ('-date_created',),
                'indexes': [models.Index(fields=['token'], name='authenticat_token_04f9aa_idx'), models.Index(fields=['token', 'status'], name='authenticat_token_1485ad_idx'), models.Index(fields=['user', 'device', 'status'], name='authenticat_user_id_4521c8_idx')],
            },
        ),
    ]
