# Generated by Django 5.2.5 on 2025-08-09 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_data', models.JSONField(blank=True, default=dict, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict, null=True)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('successful', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
                'indexes': [models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['successful'], name='audit_audit_success_ae9630_idx')],
            },
        ),
    ]
