# Generated by Django 5.2.5 on 2025-10-22 09:37

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('model_name', models.CharField(max_length=100, unique=True, verbose_name='Model Name')),
                ('app_label', models.CharField(max_length=100, verbose_name='App Label')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('track_create', models.BooleanField(default=True, verbose_name='Track Create')),
                ('track_update', models.BooleanField(default=True, verbose_name='Track Update')),
                ('track_delete', models.BooleanField(default=True, verbose_name='Track Delete')),
                ('excluded_fields', models.JSONField(blank=True, default=list, verbose_name='Excluded Fields')),
                ('retention_days', models.PositiveIntegerField(default=2555, verbose_name='Retention Days')),
            ],
            options={
                'verbose_name': 'Audit Configuration',
                'verbose_name_plural': 'Audit Configurations',
                'ordering': ['app_label', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('request_id', models.UUIDField(editable=False, verbose_name='Request ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='Is Authenticated')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Session Key')),
                ('request_method', models.CharField(max_length=10, verbose_name='Request Method')),
                ('request_path', models.TextField(verbose_name='Request Path')),
                ('is_secure', models.BooleanField(default=False, verbose_name='Is Secure')),
                ('view_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='View Name')),
                ('view_args', models.JSONField(blank=True, null=True, verbose_name='View Args')),
                ('view_kwargs', models.JSONField(blank=True, null=True, verbose_name='View Kwargs')),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Activity Name')),
                ('exception_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Exception Type')),
                ('exception_message', models.TextField(blank=True, null=True, verbose_name='Exception Message')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('time_taken', models.FloatField(blank=True, null=True, verbose_name='Time Taken (s)')),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Response Status')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Response Data')),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-date_created'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_action_86e815_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_success_ae9630_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='request_data',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='response_data',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='response_status_code',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='successful',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='activity_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Activity Name'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Changes'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('permission_change', 'Permission Change'), ('data_export', 'Data Export'), ('bulk_operation', 'Bulk Operation'), ('system_event', 'System Event'), ('security_event', 'Security Event')], db_index=True, default='', max_length=50, verbose_name='Event Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Object ID'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Object Representation'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Request ID'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=20, verbose_name='Severity'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_method',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Request Method'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_path',
            field=models.TextField(blank=True, null=True, verbose_name='Request Path'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['date_created', 'event_type'], name='audit_audit_date_cr_2e991f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'date_created'], name='audit_audit_severit_3d99c2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['request_id'], name='audit_audit_request_06fe30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditconfiguration',
            unique_together={('app_label', 'model_name')},
        ),
        migrations.AddField(
            model_name='requestlog',
            name='api_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.apiclient', verbose_name='API Client'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['started_at'], name='audit_reque_started_7c491f_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['ended_at'], name='audit_reque_ended_a_f6ffa4_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['time_taken'], name='audit_reque_time_ta_6b98fe_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['request_method'], name='audit_reque_request_865d49_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['is_authenticated'], name='audit_reque_is_auth_cbcca9_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['activity_name'], name='audit_reque_activit_c0dab5_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['view_name'], name='audit_reque_view_na_ddf60d_idx'),
        ),
    ]
