# Generated by Django 5.2.5 on 2025-10-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('audit', '0002_auditconfiguration_requestlog_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='api_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.apiclient', verbose_name='API Client'),
        ),
    ]
