# Generated by Django 5.2.5 on 2025-10-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_api_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='request_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Request Data'),
        ),
    ]
