"""
Django settings for mchangohub project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(ibgc(9bzd604@(g3a@w6@zo+6sd2ogq6#9wsky12lny21&p!^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',
    'django_celery_beat',
    'api',
    'audit',
    'authentication',
    'base',
    'contributions',
    'notifications',
    'otps',
    'users',
    'billing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mchangohub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mchangohub.wsgi.application'
AUTH_USER_MODEL = "users.User"


CSRF_ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
	'https://zentu.rentwaveafrica.co.ke'
]
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
#
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql',
		'NAME': os.environ.get('POSTGRES_DB'),
		'USER': os.environ.get('POSTGRES_USER'),
		'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
		'HOST': os.environ.get('POSTGRES_HOST'),
		'PORT': os.environ.get('POSTGRES_PORT'),
	}
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://localhost:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 100,
                'retry_on_timeout': True,
            },
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
        },
        'KEY_PREFIX': 'pesaway',
        'VERSION': 1,
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 3600  # 1 hour


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Where collectstatic will store static files

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_COUNTRY_CODE = "254"
PHONE_NUMBER_LENGTH = 12

TOKEN_VALIDITY_SECONDS = 3600

OTP_LENGTH = 4
OTP_VALIDITY_SECONDS = 3600
ACTION_OTP_VALIDITY_SECONDS = 360
OTP_MAX_RETRIES = 5

QUEUE_NOTIFICATIONS = False
NOTIFY_BASE_URL = "https://notify.rentwaveafrica.co.ke"


""" RabbitMQ configs """
RABBITMQ_USER = os.environ.get('RABBITMQ_USER')
RABBITMQ_PASSWORD = os.environ.get('RABBITMQ_PASSWORD')
RABBITMQ_HOST = os.environ.get('RABBITMQ_HOST')
RABBITMQ_VHOST = os.environ.get('RABBITMQ_VHOST')
RABBITMQ_PORT = os.environ.get('RABBITMQ_PORT')

""" Celery configs """
# CELERY_BROKER_URL = f'amqp://{RABBITMQ_USER}:{RABBITMQ_PASSWORD}@{RABBITMQ_HOST}:{RABBITMQ_PORT}/{RABBITMQ_VHOST}'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'
CELERY_BROKER_URL = os.environ.get('REDIS_URL')

# PESAWAY_CLIENT_SECRET= os.environ.get('PESAWAY_CLIENT_SECRET')
# PESAWAY_CLIENT_ID= os.environ.get('PESAWAY_CLIENT_ID')
# PESAWAY_BASE_URL= os.environ.get('PESAWAY_BASE_URL')
# PESAWAY_B2C_CALLBACK= os.environ.get('PESAWAY_B2C_CALLBACK')
# PESAWAY_C2B_CALLBACK= os.environ.get('PESAWAY_C2B_CALLBACK')

# PESAWAY_BASE_URL = os.getenv('PESAWAY_BASE_URL', 'https://api.pesaway.com')


PESAWAY_RATE_LIMIT_PER_MINUTE = int(os.getenv('PESAWAY_RATE_LIMIT_PER_MINUTE', 1000))

REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

PESAWAY_MAX_CONNECTIONS = int(os.getenv('PESAWAY_MAX_CONNECTIONS', 100))
PESAWAY_MAX_CONCURRENT_REQUESTS = int(os.getenv('PESAWAY_MAX_CONCURRENT_REQUESTS', 50))
PESAWAY_REQUEST_TIMEOUT = int(os.getenv('PESAWAY_REQUEST_TIMEOUT', 30))

CIRCUIT_BREAKER_FAILURE_THRESHOLD = int(os.getenv('CIRCUIT_BREAKER_FAILURE_THRESHOLD', 5))
CIRCUIT_BREAKER_TIMEOUT = int(os.getenv('CIRCUIT_BREAKER_TIMEOUT', 60))

PESAWAY_CLIENT_SECRET = "S9zRS9Q3f7DBkC7I"
PESAWAY_CLIENT_ID = "4yN4wTqhNDRRKY6oMksGVbTa9Q8xP0px"
PESAWAY_BASE_URL = "https://api.sandbox.pesaway.com"
PESAWAY_B2C_CALLBACK = "https://zentu.rentwaveafrica.co.ke/billing/api/v1/callbacks/b2c/"
PESAWAY_C2B_CALLBACK = "https://zentu.rentwaveafrica.co.ke/billing/api/v1/callbacks/c2b/"