# Generated by Django 5.2.5 on 2025-08-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_balanceentrytype_state_entrytype_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
