# Generated by Django 5.2.5 on 2025-10-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_state_abbreviation_state_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountfieldtype',
            name='description',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='balanceentrytype',
            name='description',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='entrytype',
            name='description',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='executionprofile',
            name='description',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='ruleprofile',
            name='description',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='ruleprofilecommand',
            name='description',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
