# Generated by Django 5.2.5 on 2025-08-09 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('delivery_method', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('PUSH', 'Push')], default='PUSH', max_length=10)),
                ('context', models.JSONField(default=dict)),
                ('template', models.CharField(max_length=20)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='ONCE', max_length=20)),
                ('unique_key', models.CharField(blank=True, help_text='Unique key to identify the notification. Generated when saving the notification', max_length=255, null=True, unique=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('CONFIRMATION_PENDING', 'Confirmation Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
                'indexes': [models.Index(fields=['user', 'date_created'], name='notificatio_user_id_9d79a3_idx'), models.Index(fields=['unique_key'], name='notificatio_unique__d3119b_idx')],
            },
        ),
    ]
