# Generated by Django 5.2.5 on 2025-08-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.JSONField(default=list, help_text='List of recipients for the notification.'),
        ),
    ]
