# Generated by Django 5.2.5 on 2025-08-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.CharField(max_length=100),
        ),
    ]
